// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See Vpicorv32_wrapper.h for the primary calling header

#ifndef _VPICORV32_WRAPPER_AXI4_MEM_PERIPH_H_
#define _VPICORV32_WRAPPER_AXI4_MEM_PERIPH_H_  // guard

#include "verilated_heavy.h"
#include "Vpicorv32_wrapper__Dpi.h"

//==========

class Vpicorv32_wrapper__Syms;
class Vpicorv32_wrapper_VerilatedVcd;
class Vpicorv32_wrapper_bm__D20_N1;
class Vpicorv32_wrapper_bm__D20_N2;
class Vpicorv32_wrapper_bm__D20_N3;
class Vpicorv32_wrapper_bm__D20_N4;


//----------

VL_MODULE(Vpicorv32_wrapper_axi4_mem_periph) {
  public:
    // CELLS
    Vpicorv32_wrapper_bm__D20_N1* __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__0__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i;
    Vpicorv32_wrapper_bm__D20_N1* __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__0__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__1__KET____DOT__bm_i;
    Vpicorv32_wrapper_bm__D20_N1* __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__0__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__2__KET____DOT__bm_i;
    Vpicorv32_wrapper_bm__D20_N1* __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__0__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__3__KET____DOT__bm_i;
    Vpicorv32_wrapper_bm__D20_N1* __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__0__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__4__KET____DOT__bm_i;
    Vpicorv32_wrapper_bm__D20_N1* __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__0__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__5__KET____DOT__bm_i;
    Vpicorv32_wrapper_bm__D20_N1* __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__0__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__6__KET____DOT__bm_i;
    Vpicorv32_wrapper_bm__D20_N1* __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__0__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__7__KET____DOT__bm_i;
    Vpicorv32_wrapper_bm__D20_N1* __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__0__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__8__KET____DOT__bm_i;
    Vpicorv32_wrapper_bm__D20_N1* __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__0__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__9__KET____DOT__bm_i;
    Vpicorv32_wrapper_bm__D20_N1* __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__0__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__10__KET____DOT__bm_i;
    Vpicorv32_wrapper_bm__D20_N1* __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__0__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__11__KET____DOT__bm_i;
    Vpicorv32_wrapper_bm__D20_N1* __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__0__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__12__KET____DOT__bm_i;
    Vpicorv32_wrapper_bm__D20_N1* __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__0__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__13__KET____DOT__bm_i;
    Vpicorv32_wrapper_bm__D20_N1* __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__0__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__14__KET____DOT__bm_i;
    Vpicorv32_wrapper_bm__D20_N1* __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__0__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__15__KET____DOT__bm_i;
    Vpicorv32_wrapper_bm__D20_N2* __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__1__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i;
    Vpicorv32_wrapper_bm__D20_N2* __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__1__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__1__KET____DOT__bm_i;
    Vpicorv32_wrapper_bm__D20_N2* __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__1__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__2__KET____DOT__bm_i;
    Vpicorv32_wrapper_bm__D20_N2* __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__1__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__3__KET____DOT__bm_i;
    Vpicorv32_wrapper_bm__D20_N2* __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__1__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__4__KET____DOT__bm_i;
    Vpicorv32_wrapper_bm__D20_N2* __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__1__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__5__KET____DOT__bm_i;
    Vpicorv32_wrapper_bm__D20_N2* __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__1__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__6__KET____DOT__bm_i;
    Vpicorv32_wrapper_bm__D20_N2* __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__1__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__7__KET____DOT__bm_i;
    Vpicorv32_wrapper_bm__D20_N3* __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__2__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i;
    Vpicorv32_wrapper_bm__D20_N3* __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__2__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__1__KET____DOT__bm_i;
    Vpicorv32_wrapper_bm__D20_N3* __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__2__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__2__KET____DOT__bm_i;
    Vpicorv32_wrapper_bm__D20_N3* __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__2__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__3__KET____DOT__bm_i;
    Vpicorv32_wrapper_bm__D20_N4* __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__3__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i;
    Vpicorv32_wrapper_bm__D20_N4* __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__3__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__1__KET____DOT__bm_i;
    
    // PORTS
    VL_IN8(__PVT__clk,0,0);
    VL_IN8(__PVT__mem_axi_awvalid,0,0);
    VL_OUT8(__PVT__mem_axi_awready,0,0);
    VL_IN8(__PVT__mem_axi_awprot,2,0);
    VL_IN8(__PVT__mem_axi_wvalid,0,0);
    VL_OUT8(__PVT__mem_axi_wready,0,0);
    VL_IN8(__PVT__mem_axi_wstrb,3,0);
    VL_OUT8(__PVT__mem_axi_bvalid,0,0);
    VL_IN8(__PVT__mem_axi_bready,0,0);
    VL_IN8(__PVT__mem_axi_arvalid,0,0);
    VL_OUT8(__PVT__mem_axi_arready,0,0);
    VL_IN8(__PVT__mem_axi_arprot,2,0);
    VL_OUT8(__PVT__mem_axi_rvalid,0,0);
    VL_IN8(__PVT__mem_axi_rready,0,0);
    VL_OUT8(__PVT__tests_passed,0,0);
    VL_IN(__PVT__mem_axi_awaddr,31,0);
    VL_IN(__PVT__mem_axi_wdata,31,0);
    VL_IN(__PVT__mem_axi_araddr,31,0);
    VL_OUT(__PVT__mem_axi_rdata,31,0);
    
    // LOCAL SIGNALS
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        CData/*0:0*/ __PVT__verbose;
        CData/*0:0*/ __PVT__rst;
        CData/*0:0*/ __PVT__now1;
        CData/*0:0*/ __PVT__now2;
        CData/*0:0*/ __PVT__latched_raddr_en;
        CData/*0:0*/ __PVT__latched_waddr_en;
        CData/*0:0*/ __PVT__latched_wdata_en;
        CData/*0:0*/ __PVT__fast_raddr;
        CData/*0:0*/ __PVT__fast_waddr;
        CData/*0:0*/ __PVT__fast_wdata;
        CData/*3:0*/ __PVT__latched_wstrb;
        CData/*0:0*/ __PVT__latched_rinsn;
        CData/*0:0*/ __PVT__M__DOT__prev1;
        CData/*0:0*/ __PVT__M__DOT__prev2;
        CData/*0:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__x_valid_stage;
        CData/*0:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__last_stage;
        CData/*0:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__0__KET____DOT__vls;
        CData/*0:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__1__KET____DOT__vls;
        CData/*0:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__2__KET____DOT__vls;
        CData/*0:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__3__KET____DOT__vls;
        CData/*0:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__0__KET____DOT__y_valid_ch;
        CData/*0:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__1__KET____DOT__y_valid_ch;
        CData/*0:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__2__KET____DOT__y_valid_ch;
        CData/*0:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__3__KET____DOT__y_valid_ch;
        CData/*0:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__4__KET____DOT__y_valid_ch;
        CData/*4:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__2__KET____DOT__bm_chann_i__DOT__genblk1__BRA__0__KET____DOT__validp;
        CData/*4:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__2__KET____DOT__bm_chann_i__DOT__genblk1__BRA__1__KET____DOT__validp;
        CData/*4:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__2__KET____DOT__bm_chann_i__DOT__genblk1__BRA__2__KET____DOT__validp;
        CData/*4:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__2__KET____DOT__bm_chann_i__DOT__genblk1__BRA__3__KET____DOT__validp;
        CData/*2:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__3__KET____DOT__bm_chann_i__DOT__genblk1__BRA__0__KET____DOT__validp;
        CData/*2:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__3__KET____DOT__bm_chann_i__DOT__genblk1__BRA__1__KET____DOT__validp;
        CData/*2:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__3__KET____DOT__bm_chann_i__DOT__genblk1__BRA__2__KET____DOT__validp;
        CData/*2:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__3__KET____DOT__bm_chann_i__DOT__genblk1__BRA__3__KET____DOT__validp;
        CData/*2:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__3__KET____DOT__bm_chann_i__DOT__genblk1__BRA__4__KET____DOT__validp;
        CData/*2:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__3__KET____DOT__bm_chann_i__DOT__genblk1__BRA__5__KET____DOT__validp;
        CData/*2:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__3__KET____DOT__bm_chann_i__DOT__genblk1__BRA__6__KET____DOT__validp;
        CData/*2:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__3__KET____DOT__bm_chann_i__DOT__genblk1__BRA__7__KET____DOT__validp;
        CData/*1:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__4__KET____DOT__bm_chann_i__DOT__genblk1__BRA__0__KET____DOT__validp;
        CData/*1:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__4__KET____DOT__bm_chann_i__DOT__genblk1__BRA__1__KET____DOT__validp;
        CData/*1:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__4__KET____DOT__bm_chann_i__DOT__genblk1__BRA__2__KET____DOT__validp;
        CData/*1:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__4__KET____DOT__bm_chann_i__DOT__genblk1__BRA__3__KET____DOT__validp;
        CData/*1:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__4__KET____DOT__bm_chann_i__DOT__genblk1__BRA__4__KET____DOT__validp;
        CData/*1:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__4__KET____DOT__bm_chann_i__DOT__genblk1__BRA__5__KET____DOT__validp;
        CData/*1:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__4__KET____DOT__bm_chann_i__DOT__genblk1__BRA__6__KET____DOT__validp;
        CData/*1:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__4__KET____DOT__bm_chann_i__DOT__genblk1__BRA__7__KET____DOT__validp;
        CData/*1:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__4__KET____DOT__bm_chann_i__DOT__genblk1__BRA__8__KET____DOT__validp;
        CData/*1:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__4__KET____DOT__bm_chann_i__DOT__genblk1__BRA__9__KET____DOT__validp;
        CData/*1:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__4__KET____DOT__bm_chann_i__DOT__genblk1__BRA__10__KET____DOT__validp;
        CData/*1:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__4__KET____DOT__bm_chann_i__DOT__genblk1__BRA__11__KET____DOT__validp;
        CData/*1:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__4__KET____DOT__bm_chann_i__DOT__genblk1__BRA__12__KET____DOT__validp;
        CData/*1:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__4__KET____DOT__bm_chann_i__DOT__genblk1__BRA__13__KET____DOT__validp;
        CData/*1:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__4__KET____DOT__bm_chann_i__DOT__genblk1__BRA__14__KET____DOT__validp;
        CData/*1:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__4__KET____DOT__bm_chann_i__DOT__genblk1__BRA__15__KET____DOT__validp;
        SData/*8:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__1__KET____DOT__bm_chann_i__DOT__genblk1__BRA__0__KET____DOT__validp;
        SData/*8:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__1__KET____DOT__bm_chann_i__DOT__genblk1__BRA__1__KET____DOT__validp;
        IData/*31:0*/ __PVT__din;
        IData/*31:0*/ __PVT__dout;
        IData/*31:0*/ __PVT__i;
        IData/*31:0*/ __PVT__out_file;
        IData/*31:0*/ __PVT__latched_raddr;
        IData/*31:0*/ __PVT__latched_waddr;
        IData/*31:0*/ __PVT__latched_wdata;
        IData/*31:0*/ __PVT__M__DOT__cnt1;
        IData/*31:0*/ __PVT__M__DOT__cnt2;
    };
    struct {
        WData/*1023:0*/ __PVT__M__DOT__x[32];
        WData/*1023:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__0__KET____DOT__out[32];
        WData/*1023:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__1__KET____DOT__out[32];
        WData/*1023:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__2__KET____DOT__out[32];
        WData/*1023:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__3__KET____DOT__out[32];
        WData/*1023:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__1__KET____DOT__out[32];
        WData/*1023:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__2__KET____DOT__out[32];
        WData/*1023:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__3__KET____DOT__out[32];
        WData/*1023:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__4__KET____DOT__out[32];
        WData/*1023:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__0__KET____DOT__bm_chann_i__DOT__genblk1__BRA__0__KET____DOT__outp[32];
        IData/*16:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__0__KET____DOT__bm_chann_i__DOT__genblk1__BRA__0__KET____DOT__validp;
        IData/*31:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__0__KET____DOT__bm_chann_i__DOT__genblk1__BRA__0__KET____DOT__bm_chann_unit_i__DOT__genblk1__BRA__0__KET____DOT__y1;
        IData/*31:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__0__KET____DOT__bm_chann_i__DOT__genblk1__BRA__0__KET____DOT__bm_chann_unit_i__DOT__genblk1__BRA__0__KET____DOT__y2;
        IData/*31:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__0__KET____DOT__bm_chann_i__DOT__genblk1__BRA__0__KET____DOT__bm_chann_unit_i__DOT__genblk1__BRA__1__KET____DOT__y1;
        IData/*31:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__0__KET____DOT__bm_chann_i__DOT__genblk1__BRA__0__KET____DOT__bm_chann_unit_i__DOT__genblk1__BRA__1__KET____DOT__y2;
        IData/*31:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__0__KET____DOT__bm_chann_i__DOT__genblk1__BRA__0__KET____DOT__bm_chann_unit_i__DOT__genblk1__BRA__2__KET____DOT__y1;
        IData/*31:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__0__KET____DOT__bm_chann_i__DOT__genblk1__BRA__0__KET____DOT__bm_chann_unit_i__DOT__genblk1__BRA__2__KET____DOT__y2;
        IData/*31:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__0__KET____DOT__bm_chann_i__DOT__genblk1__BRA__0__KET____DOT__bm_chann_unit_i__DOT__genblk1__BRA__3__KET____DOT__y1;
        IData/*31:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__0__KET____DOT__bm_chann_i__DOT__genblk1__BRA__0__KET____DOT__bm_chann_unit_i__DOT__genblk1__BRA__3__KET____DOT__y2;
        IData/*31:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__0__KET____DOT__bm_chann_i__DOT__genblk1__BRA__0__KET____DOT__bm_chann_unit_i__DOT__genblk1__BRA__4__KET____DOT__y1;
        IData/*31:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__0__KET____DOT__bm_chann_i__DOT__genblk1__BRA__0__KET____DOT__bm_chann_unit_i__DOT__genblk1__BRA__4__KET____DOT__y2;
        IData/*31:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__0__KET____DOT__bm_chann_i__DOT__genblk1__BRA__0__KET____DOT__bm_chann_unit_i__DOT__genblk1__BRA__5__KET____DOT__y1;
        IData/*31:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__0__KET____DOT__bm_chann_i__DOT__genblk1__BRA__0__KET____DOT__bm_chann_unit_i__DOT__genblk1__BRA__5__KET____DOT__y2;
        IData/*31:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__0__KET____DOT__bm_chann_i__DOT__genblk1__BRA__0__KET____DOT__bm_chann_unit_i__DOT__genblk1__BRA__6__KET____DOT__y1;
        IData/*31:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__0__KET____DOT__bm_chann_i__DOT__genblk1__BRA__0__KET____DOT__bm_chann_unit_i__DOT__genblk1__BRA__6__KET____DOT__y2;
        IData/*31:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__0__KET____DOT__bm_chann_i__DOT__genblk1__BRA__0__KET____DOT__bm_chann_unit_i__DOT__genblk1__BRA__7__KET____DOT__y1;
        IData/*31:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__0__KET____DOT__bm_chann_i__DOT__genblk1__BRA__0__KET____DOT__bm_chann_unit_i__DOT__genblk1__BRA__7__KET____DOT__y2;
        IData/*31:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__0__KET____DOT__bm_chann_i__DOT__genblk1__BRA__0__KET____DOT__bm_chann_unit_i__DOT__genblk1__BRA__8__KET____DOT__y1;
        IData/*31:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__0__KET____DOT__bm_chann_i__DOT__genblk1__BRA__0__KET____DOT__bm_chann_unit_i__DOT__genblk1__BRA__8__KET____DOT__y2;
        IData/*31:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__0__KET____DOT__bm_chann_i__DOT__genblk1__BRA__0__KET____DOT__bm_chann_unit_i__DOT__genblk1__BRA__9__KET____DOT__y1;
        IData/*31:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__0__KET____DOT__bm_chann_i__DOT__genblk1__BRA__0__KET____DOT__bm_chann_unit_i__DOT__genblk1__BRA__9__KET____DOT__y2;
        IData/*31:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__0__KET____DOT__bm_chann_i__DOT__genblk1__BRA__0__KET____DOT__bm_chann_unit_i__DOT__genblk1__BRA__10__KET____DOT__y1;
        IData/*31:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__0__KET____DOT__bm_chann_i__DOT__genblk1__BRA__0__KET____DOT__bm_chann_unit_i__DOT__genblk1__BRA__10__KET____DOT__y2;
        IData/*31:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__0__KET____DOT__bm_chann_i__DOT__genblk1__BRA__0__KET____DOT__bm_chann_unit_i__DOT__genblk1__BRA__11__KET____DOT__y1;
        IData/*31:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__0__KET____DOT__bm_chann_i__DOT__genblk1__BRA__0__KET____DOT__bm_chann_unit_i__DOT__genblk1__BRA__11__KET____DOT__y2;
        IData/*31:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__0__KET____DOT__bm_chann_i__DOT__genblk1__BRA__0__KET____DOT__bm_chann_unit_i__DOT__genblk1__BRA__12__KET____DOT__y1;
        IData/*31:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__0__KET____DOT__bm_chann_i__DOT__genblk1__BRA__0__KET____DOT__bm_chann_unit_i__DOT__genblk1__BRA__12__KET____DOT__y2;
        IData/*31:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__0__KET____DOT__bm_chann_i__DOT__genblk1__BRA__0__KET____DOT__bm_chann_unit_i__DOT__genblk1__BRA__13__KET____DOT__y1;
        IData/*31:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__0__KET____DOT__bm_chann_i__DOT__genblk1__BRA__0__KET____DOT__bm_chann_unit_i__DOT__genblk1__BRA__13__KET____DOT__y2;
        IData/*31:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__0__KET____DOT__bm_chann_i__DOT__genblk1__BRA__0__KET____DOT__bm_chann_unit_i__DOT__genblk1__BRA__14__KET____DOT__y1;
        IData/*31:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__0__KET____DOT__bm_chann_i__DOT__genblk1__BRA__0__KET____DOT__bm_chann_unit_i__DOT__genblk1__BRA__14__KET____DOT__y2;
        IData/*31:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__0__KET____DOT__bm_chann_i__DOT__genblk1__BRA__0__KET____DOT__bm_chann_unit_i__DOT__genblk1__BRA__15__KET____DOT__y1;
        IData/*31:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__0__KET____DOT__bm_chann_i__DOT__genblk1__BRA__0__KET____DOT__bm_chann_unit_i__DOT__genblk1__BRA__15__KET____DOT__y2;
        WData/*511:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__1__KET____DOT__bm_chann_i__DOT__genblk1__BRA__0__KET____DOT__outp[16];
        WData/*511:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__1__KET____DOT__bm_chann_i__DOT__genblk1__BRA__1__KET____DOT__outp[16];
        IData/*31:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__1__KET____DOT__bm_chann_i__DOT__genblk1__BRA__0__KET____DOT__bm_chann_unit_i__DOT__genblk1__BRA__0__KET____DOT__y1;
        IData/*31:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__1__KET____DOT__bm_chann_i__DOT__genblk1__BRA__0__KET____DOT__bm_chann_unit_i__DOT__genblk1__BRA__0__KET____DOT__y2;
        IData/*31:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__1__KET____DOT__bm_chann_i__DOT__genblk1__BRA__0__KET____DOT__bm_chann_unit_i__DOT__genblk1__BRA__1__KET____DOT__y1;
        IData/*31:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__1__KET____DOT__bm_chann_i__DOT__genblk1__BRA__0__KET____DOT__bm_chann_unit_i__DOT__genblk1__BRA__1__KET____DOT__y2;
        IData/*31:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__1__KET____DOT__bm_chann_i__DOT__genblk1__BRA__0__KET____DOT__bm_chann_unit_i__DOT__genblk1__BRA__2__KET____DOT__y1;
        IData/*31:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__1__KET____DOT__bm_chann_i__DOT__genblk1__BRA__0__KET____DOT__bm_chann_unit_i__DOT__genblk1__BRA__2__KET____DOT__y2;
        IData/*31:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__1__KET____DOT__bm_chann_i__DOT__genblk1__BRA__0__KET____DOT__bm_chann_unit_i__DOT__genblk1__BRA__3__KET____DOT__y1;
        IData/*31:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__1__KET____DOT__bm_chann_i__DOT__genblk1__BRA__0__KET____DOT__bm_chann_unit_i__DOT__genblk1__BRA__3__KET____DOT__y2;
        IData/*31:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__1__KET____DOT__bm_chann_i__DOT__genblk1__BRA__0__KET____DOT__bm_chann_unit_i__DOT__genblk1__BRA__4__KET____DOT__y1;
        IData/*31:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__1__KET____DOT__bm_chann_i__DOT__genblk1__BRA__0__KET____DOT__bm_chann_unit_i__DOT__genblk1__BRA__4__KET____DOT__y2;
        IData/*31:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__1__KET____DOT__bm_chann_i__DOT__genblk1__BRA__0__KET____DOT__bm_chann_unit_i__DOT__genblk1__BRA__5__KET____DOT__y1;
        IData/*31:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__1__KET____DOT__bm_chann_i__DOT__genblk1__BRA__0__KET____DOT__bm_chann_unit_i__DOT__genblk1__BRA__5__KET____DOT__y2;
        IData/*31:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__1__KET____DOT__bm_chann_i__DOT__genblk1__BRA__0__KET____DOT__bm_chann_unit_i__DOT__genblk1__BRA__6__KET____DOT__y1;
        IData/*31:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__1__KET____DOT__bm_chann_i__DOT__genblk1__BRA__0__KET____DOT__bm_chann_unit_i__DOT__genblk1__BRA__6__KET____DOT__y2;
        IData/*31:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__1__KET____DOT__bm_chann_i__DOT__genblk1__BRA__0__KET____DOT__bm_chann_unit_i__DOT__genblk1__BRA__7__KET____DOT__y1;
        IData/*31:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__1__KET____DOT__bm_chann_i__DOT__genblk1__BRA__0__KET____DOT__bm_chann_unit_i__DOT__genblk1__BRA__7__KET____DOT__y2;
        IData/*31:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__1__KET____DOT__bm_chann_i__DOT__genblk1__BRA__1__KET____DOT__bm_chann_unit_i__DOT__genblk1__BRA__0__KET____DOT__y1;
        IData/*31:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__1__KET____DOT__bm_chann_i__DOT__genblk1__BRA__1__KET____DOT__bm_chann_unit_i__DOT__genblk1__BRA__0__KET____DOT__y2;
        IData/*31:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__1__KET____DOT__bm_chann_i__DOT__genblk1__BRA__1__KET____DOT__bm_chann_unit_i__DOT__genblk1__BRA__1__KET____DOT__y1;
    };
    struct {
        IData/*31:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__1__KET____DOT__bm_chann_i__DOT__genblk1__BRA__1__KET____DOT__bm_chann_unit_i__DOT__genblk1__BRA__1__KET____DOT__y2;
        IData/*31:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__1__KET____DOT__bm_chann_i__DOT__genblk1__BRA__1__KET____DOT__bm_chann_unit_i__DOT__genblk1__BRA__2__KET____DOT__y1;
        IData/*31:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__1__KET____DOT__bm_chann_i__DOT__genblk1__BRA__1__KET____DOT__bm_chann_unit_i__DOT__genblk1__BRA__2__KET____DOT__y2;
        IData/*31:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__1__KET____DOT__bm_chann_i__DOT__genblk1__BRA__1__KET____DOT__bm_chann_unit_i__DOT__genblk1__BRA__3__KET____DOT__y1;
        IData/*31:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__1__KET____DOT__bm_chann_i__DOT__genblk1__BRA__1__KET____DOT__bm_chann_unit_i__DOT__genblk1__BRA__3__KET____DOT__y2;
        IData/*31:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__1__KET____DOT__bm_chann_i__DOT__genblk1__BRA__1__KET____DOT__bm_chann_unit_i__DOT__genblk1__BRA__4__KET____DOT__y1;
        IData/*31:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__1__KET____DOT__bm_chann_i__DOT__genblk1__BRA__1__KET____DOT__bm_chann_unit_i__DOT__genblk1__BRA__4__KET____DOT__y2;
        IData/*31:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__1__KET____DOT__bm_chann_i__DOT__genblk1__BRA__1__KET____DOT__bm_chann_unit_i__DOT__genblk1__BRA__5__KET____DOT__y1;
        IData/*31:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__1__KET____DOT__bm_chann_i__DOT__genblk1__BRA__1__KET____DOT__bm_chann_unit_i__DOT__genblk1__BRA__5__KET____DOT__y2;
        IData/*31:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__1__KET____DOT__bm_chann_i__DOT__genblk1__BRA__1__KET____DOT__bm_chann_unit_i__DOT__genblk1__BRA__6__KET____DOT__y1;
        IData/*31:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__1__KET____DOT__bm_chann_i__DOT__genblk1__BRA__1__KET____DOT__bm_chann_unit_i__DOT__genblk1__BRA__6__KET____DOT__y2;
        IData/*31:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__1__KET____DOT__bm_chann_i__DOT__genblk1__BRA__1__KET____DOT__bm_chann_unit_i__DOT__genblk1__BRA__7__KET____DOT__y1;
        IData/*31:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__1__KET____DOT__bm_chann_i__DOT__genblk1__BRA__1__KET____DOT__bm_chann_unit_i__DOT__genblk1__BRA__7__KET____DOT__y2;
        WData/*255:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__2__KET____DOT__bm_chann_i__DOT__genblk1__BRA__0__KET____DOT__outp[8];
        WData/*255:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__2__KET____DOT__bm_chann_i__DOT__genblk1__BRA__1__KET____DOT__outp[8];
        WData/*255:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__2__KET____DOT__bm_chann_i__DOT__genblk1__BRA__2__KET____DOT__outp[8];
        WData/*255:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__2__KET____DOT__bm_chann_i__DOT__genblk1__BRA__3__KET____DOT__outp[8];
        IData/*31:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__2__KET____DOT__bm_chann_i__DOT__genblk1__BRA__0__KET____DOT__bm_chann_unit_i__DOT__genblk1__BRA__0__KET____DOT__y1;
        IData/*31:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__2__KET____DOT__bm_chann_i__DOT__genblk1__BRA__0__KET____DOT__bm_chann_unit_i__DOT__genblk1__BRA__0__KET____DOT__y2;
        IData/*31:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__2__KET____DOT__bm_chann_i__DOT__genblk1__BRA__0__KET____DOT__bm_chann_unit_i__DOT__genblk1__BRA__1__KET____DOT__y1;
        IData/*31:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__2__KET____DOT__bm_chann_i__DOT__genblk1__BRA__0__KET____DOT__bm_chann_unit_i__DOT__genblk1__BRA__1__KET____DOT__y2;
        IData/*31:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__2__KET____DOT__bm_chann_i__DOT__genblk1__BRA__0__KET____DOT__bm_chann_unit_i__DOT__genblk1__BRA__2__KET____DOT__y1;
        IData/*31:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__2__KET____DOT__bm_chann_i__DOT__genblk1__BRA__0__KET____DOT__bm_chann_unit_i__DOT__genblk1__BRA__2__KET____DOT__y2;
        IData/*31:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__2__KET____DOT__bm_chann_i__DOT__genblk1__BRA__0__KET____DOT__bm_chann_unit_i__DOT__genblk1__BRA__3__KET____DOT__y1;
        IData/*31:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__2__KET____DOT__bm_chann_i__DOT__genblk1__BRA__0__KET____DOT__bm_chann_unit_i__DOT__genblk1__BRA__3__KET____DOT__y2;
        IData/*31:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__2__KET____DOT__bm_chann_i__DOT__genblk1__BRA__1__KET____DOT__bm_chann_unit_i__DOT__genblk1__BRA__0__KET____DOT__y1;
        IData/*31:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__2__KET____DOT__bm_chann_i__DOT__genblk1__BRA__1__KET____DOT__bm_chann_unit_i__DOT__genblk1__BRA__0__KET____DOT__y2;
        IData/*31:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__2__KET____DOT__bm_chann_i__DOT__genblk1__BRA__1__KET____DOT__bm_chann_unit_i__DOT__genblk1__BRA__1__KET____DOT__y1;
        IData/*31:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__2__KET____DOT__bm_chann_i__DOT__genblk1__BRA__1__KET____DOT__bm_chann_unit_i__DOT__genblk1__BRA__1__KET____DOT__y2;
        IData/*31:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__2__KET____DOT__bm_chann_i__DOT__genblk1__BRA__1__KET____DOT__bm_chann_unit_i__DOT__genblk1__BRA__2__KET____DOT__y1;
        IData/*31:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__2__KET____DOT__bm_chann_i__DOT__genblk1__BRA__1__KET____DOT__bm_chann_unit_i__DOT__genblk1__BRA__2__KET____DOT__y2;
        IData/*31:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__2__KET____DOT__bm_chann_i__DOT__genblk1__BRA__1__KET____DOT__bm_chann_unit_i__DOT__genblk1__BRA__3__KET____DOT__y1;
        IData/*31:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__2__KET____DOT__bm_chann_i__DOT__genblk1__BRA__1__KET____DOT__bm_chann_unit_i__DOT__genblk1__BRA__3__KET____DOT__y2;
        IData/*31:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__2__KET____DOT__bm_chann_i__DOT__genblk1__BRA__2__KET____DOT__bm_chann_unit_i__DOT__genblk1__BRA__0__KET____DOT__y1;
        IData/*31:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__2__KET____DOT__bm_chann_i__DOT__genblk1__BRA__2__KET____DOT__bm_chann_unit_i__DOT__genblk1__BRA__0__KET____DOT__y2;
        IData/*31:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__2__KET____DOT__bm_chann_i__DOT__genblk1__BRA__2__KET____DOT__bm_chann_unit_i__DOT__genblk1__BRA__1__KET____DOT__y1;
        IData/*31:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__2__KET____DOT__bm_chann_i__DOT__genblk1__BRA__2__KET____DOT__bm_chann_unit_i__DOT__genblk1__BRA__1__KET____DOT__y2;
        IData/*31:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__2__KET____DOT__bm_chann_i__DOT__genblk1__BRA__2__KET____DOT__bm_chann_unit_i__DOT__genblk1__BRA__2__KET____DOT__y1;
        IData/*31:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__2__KET____DOT__bm_chann_i__DOT__genblk1__BRA__2__KET____DOT__bm_chann_unit_i__DOT__genblk1__BRA__2__KET____DOT__y2;
        IData/*31:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__2__KET____DOT__bm_chann_i__DOT__genblk1__BRA__2__KET____DOT__bm_chann_unit_i__DOT__genblk1__BRA__3__KET____DOT__y1;
        IData/*31:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__2__KET____DOT__bm_chann_i__DOT__genblk1__BRA__2__KET____DOT__bm_chann_unit_i__DOT__genblk1__BRA__3__KET____DOT__y2;
        IData/*31:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__2__KET____DOT__bm_chann_i__DOT__genblk1__BRA__3__KET____DOT__bm_chann_unit_i__DOT__genblk1__BRA__0__KET____DOT__y1;
        IData/*31:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__2__KET____DOT__bm_chann_i__DOT__genblk1__BRA__3__KET____DOT__bm_chann_unit_i__DOT__genblk1__BRA__0__KET____DOT__y2;
        IData/*31:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__2__KET____DOT__bm_chann_i__DOT__genblk1__BRA__3__KET____DOT__bm_chann_unit_i__DOT__genblk1__BRA__1__KET____DOT__y1;
        IData/*31:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__2__KET____DOT__bm_chann_i__DOT__genblk1__BRA__3__KET____DOT__bm_chann_unit_i__DOT__genblk1__BRA__1__KET____DOT__y2;
        IData/*31:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__2__KET____DOT__bm_chann_i__DOT__genblk1__BRA__3__KET____DOT__bm_chann_unit_i__DOT__genblk1__BRA__2__KET____DOT__y1;
        IData/*31:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__2__KET____DOT__bm_chann_i__DOT__genblk1__BRA__3__KET____DOT__bm_chann_unit_i__DOT__genblk1__BRA__2__KET____DOT__y2;
        IData/*31:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__2__KET____DOT__bm_chann_i__DOT__genblk1__BRA__3__KET____DOT__bm_chann_unit_i__DOT__genblk1__BRA__3__KET____DOT__y1;
        IData/*31:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__2__KET____DOT__bm_chann_i__DOT__genblk1__BRA__3__KET____DOT__bm_chann_unit_i__DOT__genblk1__BRA__3__KET____DOT__y2;
        WData/*127:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__3__KET____DOT__bm_chann_i__DOT__genblk1__BRA__0__KET____DOT__outp[4];
        WData/*127:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__3__KET____DOT__bm_chann_i__DOT__genblk1__BRA__1__KET____DOT__outp[4];
        WData/*127:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__3__KET____DOT__bm_chann_i__DOT__genblk1__BRA__2__KET____DOT__outp[4];
        WData/*127:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__3__KET____DOT__bm_chann_i__DOT__genblk1__BRA__3__KET____DOT__outp[4];
        WData/*127:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__3__KET____DOT__bm_chann_i__DOT__genblk1__BRA__4__KET____DOT__outp[4];
        WData/*127:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__3__KET____DOT__bm_chann_i__DOT__genblk1__BRA__5__KET____DOT__outp[4];
        WData/*127:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__3__KET____DOT__bm_chann_i__DOT__genblk1__BRA__6__KET____DOT__outp[4];
        WData/*127:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__3__KET____DOT__bm_chann_i__DOT__genblk1__BRA__7__KET____DOT__outp[4];
        IData/*31:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__3__KET____DOT__bm_chann_i__DOT__genblk1__BRA__0__KET____DOT__bm_chann_unit_i__DOT__genblk1__BRA__0__KET____DOT__y1;
        IData/*31:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__3__KET____DOT__bm_chann_i__DOT__genblk1__BRA__0__KET____DOT__bm_chann_unit_i__DOT__genblk1__BRA__0__KET____DOT__y2;
        IData/*31:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__3__KET____DOT__bm_chann_i__DOT__genblk1__BRA__0__KET____DOT__bm_chann_unit_i__DOT__genblk1__BRA__1__KET____DOT__y1;
        IData/*31:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__3__KET____DOT__bm_chann_i__DOT__genblk1__BRA__0__KET____DOT__bm_chann_unit_i__DOT__genblk1__BRA__1__KET____DOT__y2;
        IData/*31:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__3__KET____DOT__bm_chann_i__DOT__genblk1__BRA__1__KET____DOT__bm_chann_unit_i__DOT__genblk1__BRA__0__KET____DOT__y1;
        IData/*31:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__3__KET____DOT__bm_chann_i__DOT__genblk1__BRA__1__KET____DOT__bm_chann_unit_i__DOT__genblk1__BRA__0__KET____DOT__y2;
        IData/*31:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__3__KET____DOT__bm_chann_i__DOT__genblk1__BRA__1__KET____DOT__bm_chann_unit_i__DOT__genblk1__BRA__1__KET____DOT__y1;
    };
    struct {
        IData/*31:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__3__KET____DOT__bm_chann_i__DOT__genblk1__BRA__1__KET____DOT__bm_chann_unit_i__DOT__genblk1__BRA__1__KET____DOT__y2;
        IData/*31:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__3__KET____DOT__bm_chann_i__DOT__genblk1__BRA__2__KET____DOT__bm_chann_unit_i__DOT__genblk1__BRA__0__KET____DOT__y1;
        IData/*31:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__3__KET____DOT__bm_chann_i__DOT__genblk1__BRA__2__KET____DOT__bm_chann_unit_i__DOT__genblk1__BRA__0__KET____DOT__y2;
        IData/*31:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__3__KET____DOT__bm_chann_i__DOT__genblk1__BRA__2__KET____DOT__bm_chann_unit_i__DOT__genblk1__BRA__1__KET____DOT__y1;
        IData/*31:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__3__KET____DOT__bm_chann_i__DOT__genblk1__BRA__2__KET____DOT__bm_chann_unit_i__DOT__genblk1__BRA__1__KET____DOT__y2;
        IData/*31:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__3__KET____DOT__bm_chann_i__DOT__genblk1__BRA__3__KET____DOT__bm_chann_unit_i__DOT__genblk1__BRA__0__KET____DOT__y1;
        IData/*31:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__3__KET____DOT__bm_chann_i__DOT__genblk1__BRA__3__KET____DOT__bm_chann_unit_i__DOT__genblk1__BRA__0__KET____DOT__y2;
        IData/*31:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__3__KET____DOT__bm_chann_i__DOT__genblk1__BRA__3__KET____DOT__bm_chann_unit_i__DOT__genblk1__BRA__1__KET____DOT__y1;
        IData/*31:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__3__KET____DOT__bm_chann_i__DOT__genblk1__BRA__3__KET____DOT__bm_chann_unit_i__DOT__genblk1__BRA__1__KET____DOT__y2;
        IData/*31:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__3__KET____DOT__bm_chann_i__DOT__genblk1__BRA__4__KET____DOT__bm_chann_unit_i__DOT__genblk1__BRA__0__KET____DOT__y1;
        IData/*31:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__3__KET____DOT__bm_chann_i__DOT__genblk1__BRA__4__KET____DOT__bm_chann_unit_i__DOT__genblk1__BRA__0__KET____DOT__y2;
        IData/*31:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__3__KET____DOT__bm_chann_i__DOT__genblk1__BRA__4__KET____DOT__bm_chann_unit_i__DOT__genblk1__BRA__1__KET____DOT__y1;
        IData/*31:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__3__KET____DOT__bm_chann_i__DOT__genblk1__BRA__4__KET____DOT__bm_chann_unit_i__DOT__genblk1__BRA__1__KET____DOT__y2;
        IData/*31:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__3__KET____DOT__bm_chann_i__DOT__genblk1__BRA__5__KET____DOT__bm_chann_unit_i__DOT__genblk1__BRA__0__KET____DOT__y1;
        IData/*31:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__3__KET____DOT__bm_chann_i__DOT__genblk1__BRA__5__KET____DOT__bm_chann_unit_i__DOT__genblk1__BRA__0__KET____DOT__y2;
        IData/*31:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__3__KET____DOT__bm_chann_i__DOT__genblk1__BRA__5__KET____DOT__bm_chann_unit_i__DOT__genblk1__BRA__1__KET____DOT__y1;
        IData/*31:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__3__KET____DOT__bm_chann_i__DOT__genblk1__BRA__5__KET____DOT__bm_chann_unit_i__DOT__genblk1__BRA__1__KET____DOT__y2;
        IData/*31:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__3__KET____DOT__bm_chann_i__DOT__genblk1__BRA__6__KET____DOT__bm_chann_unit_i__DOT__genblk1__BRA__0__KET____DOT__y1;
        IData/*31:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__3__KET____DOT__bm_chann_i__DOT__genblk1__BRA__6__KET____DOT__bm_chann_unit_i__DOT__genblk1__BRA__0__KET____DOT__y2;
        IData/*31:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__3__KET____DOT__bm_chann_i__DOT__genblk1__BRA__6__KET____DOT__bm_chann_unit_i__DOT__genblk1__BRA__1__KET____DOT__y1;
        IData/*31:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__3__KET____DOT__bm_chann_i__DOT__genblk1__BRA__6__KET____DOT__bm_chann_unit_i__DOT__genblk1__BRA__1__KET____DOT__y2;
        IData/*31:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__3__KET____DOT__bm_chann_i__DOT__genblk1__BRA__7__KET____DOT__bm_chann_unit_i__DOT__genblk1__BRA__0__KET____DOT__y1;
        IData/*31:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__3__KET____DOT__bm_chann_i__DOT__genblk1__BRA__7__KET____DOT__bm_chann_unit_i__DOT__genblk1__BRA__0__KET____DOT__y2;
        IData/*31:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__3__KET____DOT__bm_chann_i__DOT__genblk1__BRA__7__KET____DOT__bm_chann_unit_i__DOT__genblk1__BRA__1__KET____DOT__y1;
        IData/*31:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__3__KET____DOT__bm_chann_i__DOT__genblk1__BRA__7__KET____DOT__bm_chann_unit_i__DOT__genblk1__BRA__1__KET____DOT__y2;
        IData/*31:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__4__KET____DOT__bm_chann_i__DOT__genblk1__BRA__0__KET____DOT__bm_chann_unit_i__DOT__genblk1__BRA__0__KET____DOT__y1;
        IData/*31:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__4__KET____DOT__bm_chann_i__DOT__genblk1__BRA__0__KET____DOT__bm_chann_unit_i__DOT__genblk1__BRA__0__KET____DOT__y2;
        IData/*31:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__4__KET____DOT__bm_chann_i__DOT__genblk1__BRA__1__KET____DOT__bm_chann_unit_i__DOT__genblk1__BRA__0__KET____DOT__y1;
        IData/*31:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__4__KET____DOT__bm_chann_i__DOT__genblk1__BRA__1__KET____DOT__bm_chann_unit_i__DOT__genblk1__BRA__0__KET____DOT__y2;
        IData/*31:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__4__KET____DOT__bm_chann_i__DOT__genblk1__BRA__2__KET____DOT__bm_chann_unit_i__DOT__genblk1__BRA__0__KET____DOT__y1;
        IData/*31:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__4__KET____DOT__bm_chann_i__DOT__genblk1__BRA__2__KET____DOT__bm_chann_unit_i__DOT__genblk1__BRA__0__KET____DOT__y2;
        IData/*31:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__4__KET____DOT__bm_chann_i__DOT__genblk1__BRA__3__KET____DOT__bm_chann_unit_i__DOT__genblk1__BRA__0__KET____DOT__y1;
        IData/*31:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__4__KET____DOT__bm_chann_i__DOT__genblk1__BRA__3__KET____DOT__bm_chann_unit_i__DOT__genblk1__BRA__0__KET____DOT__y2;
        IData/*31:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__4__KET____DOT__bm_chann_i__DOT__genblk1__BRA__4__KET____DOT__bm_chann_unit_i__DOT__genblk1__BRA__0__KET____DOT__y1;
        IData/*31:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__4__KET____DOT__bm_chann_i__DOT__genblk1__BRA__4__KET____DOT__bm_chann_unit_i__DOT__genblk1__BRA__0__KET____DOT__y2;
        IData/*31:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__4__KET____DOT__bm_chann_i__DOT__genblk1__BRA__5__KET____DOT__bm_chann_unit_i__DOT__genblk1__BRA__0__KET____DOT__y1;
        IData/*31:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__4__KET____DOT__bm_chann_i__DOT__genblk1__BRA__5__KET____DOT__bm_chann_unit_i__DOT__genblk1__BRA__0__KET____DOT__y2;
        IData/*31:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__4__KET____DOT__bm_chann_i__DOT__genblk1__BRA__6__KET____DOT__bm_chann_unit_i__DOT__genblk1__BRA__0__KET____DOT__y1;
        IData/*31:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__4__KET____DOT__bm_chann_i__DOT__genblk1__BRA__6__KET____DOT__bm_chann_unit_i__DOT__genblk1__BRA__0__KET____DOT__y2;
        IData/*31:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__4__KET____DOT__bm_chann_i__DOT__genblk1__BRA__7__KET____DOT__bm_chann_unit_i__DOT__genblk1__BRA__0__KET____DOT__y1;
        IData/*31:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__4__KET____DOT__bm_chann_i__DOT__genblk1__BRA__7__KET____DOT__bm_chann_unit_i__DOT__genblk1__BRA__0__KET____DOT__y2;
        IData/*31:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__4__KET____DOT__bm_chann_i__DOT__genblk1__BRA__8__KET____DOT__bm_chann_unit_i__DOT__genblk1__BRA__0__KET____DOT__y1;
        IData/*31:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__4__KET____DOT__bm_chann_i__DOT__genblk1__BRA__8__KET____DOT__bm_chann_unit_i__DOT__genblk1__BRA__0__KET____DOT__y2;
        IData/*31:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__4__KET____DOT__bm_chann_i__DOT__genblk1__BRA__9__KET____DOT__bm_chann_unit_i__DOT__genblk1__BRA__0__KET____DOT__y1;
        IData/*31:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__4__KET____DOT__bm_chann_i__DOT__genblk1__BRA__9__KET____DOT__bm_chann_unit_i__DOT__genblk1__BRA__0__KET____DOT__y2;
        IData/*31:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__4__KET____DOT__bm_chann_i__DOT__genblk1__BRA__10__KET____DOT__bm_chann_unit_i__DOT__genblk1__BRA__0__KET____DOT__y1;
        IData/*31:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__4__KET____DOT__bm_chann_i__DOT__genblk1__BRA__10__KET____DOT__bm_chann_unit_i__DOT__genblk1__BRA__0__KET____DOT__y2;
        IData/*31:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__4__KET____DOT__bm_chann_i__DOT__genblk1__BRA__11__KET____DOT__bm_chann_unit_i__DOT__genblk1__BRA__0__KET____DOT__y1;
        IData/*31:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__4__KET____DOT__bm_chann_i__DOT__genblk1__BRA__11__KET____DOT__bm_chann_unit_i__DOT__genblk1__BRA__0__KET____DOT__y2;
        IData/*31:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__4__KET____DOT__bm_chann_i__DOT__genblk1__BRA__12__KET____DOT__bm_chann_unit_i__DOT__genblk1__BRA__0__KET____DOT__y1;
        IData/*31:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__4__KET____DOT__bm_chann_i__DOT__genblk1__BRA__12__KET____DOT__bm_chann_unit_i__DOT__genblk1__BRA__0__KET____DOT__y2;
        IData/*31:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__4__KET____DOT__bm_chann_i__DOT__genblk1__BRA__13__KET____DOT__bm_chann_unit_i__DOT__genblk1__BRA__0__KET____DOT__y1;
        IData/*31:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__4__KET____DOT__bm_chann_i__DOT__genblk1__BRA__13__KET____DOT__bm_chann_unit_i__DOT__genblk1__BRA__0__KET____DOT__y2;
        IData/*31:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__4__KET____DOT__bm_chann_i__DOT__genblk1__BRA__14__KET____DOT__bm_chann_unit_i__DOT__genblk1__BRA__0__KET____DOT__y1;
        IData/*31:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__4__KET____DOT__bm_chann_i__DOT__genblk1__BRA__14__KET____DOT__bm_chann_unit_i__DOT__genblk1__BRA__0__KET____DOT__y2;
        IData/*31:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__4__KET____DOT__bm_chann_i__DOT__genblk1__BRA__15__KET____DOT__bm_chann_unit_i__DOT__genblk1__BRA__0__KET____DOT__y1;
        IData/*31:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__4__KET____DOT__bm_chann_i__DOT__genblk1__BRA__15__KET____DOT__bm_chann_unit_i__DOT__genblk1__BRA__0__KET____DOT__y2;
        QData/*63:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__4__KET____DOT__bm_chann_i__DOT__genblk1__BRA__0__KET____DOT__outp;
        QData/*63:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__4__KET____DOT__bm_chann_i__DOT__genblk1__BRA__1__KET____DOT__outp;
        QData/*63:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__4__KET____DOT__bm_chann_i__DOT__genblk1__BRA__2__KET____DOT__outp;
        QData/*63:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__4__KET____DOT__bm_chann_i__DOT__genblk1__BRA__3__KET____DOT__outp;
        QData/*63:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__4__KET____DOT__bm_chann_i__DOT__genblk1__BRA__4__KET____DOT__outp;
        QData/*63:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__4__KET____DOT__bm_chann_i__DOT__genblk1__BRA__5__KET____DOT__outp;
        QData/*63:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__4__KET____DOT__bm_chann_i__DOT__genblk1__BRA__6__KET____DOT__outp;
    };
    struct {
        QData/*63:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__4__KET____DOT__bm_chann_i__DOT__genblk1__BRA__7__KET____DOT__outp;
        QData/*63:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__4__KET____DOT__bm_chann_i__DOT__genblk1__BRA__8__KET____DOT__outp;
        QData/*63:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__4__KET____DOT__bm_chann_i__DOT__genblk1__BRA__9__KET____DOT__outp;
        QData/*63:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__4__KET____DOT__bm_chann_i__DOT__genblk1__BRA__10__KET____DOT__outp;
        QData/*63:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__4__KET____DOT__bm_chann_i__DOT__genblk1__BRA__11__KET____DOT__outp;
        QData/*63:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__4__KET____DOT__bm_chann_i__DOT__genblk1__BRA__12__KET____DOT__outp;
        QData/*63:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__4__KET____DOT__bm_chann_i__DOT__genblk1__BRA__13__KET____DOT__outp;
        QData/*63:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__4__KET____DOT__bm_chann_i__DOT__genblk1__BRA__14__KET____DOT__outp;
        QData/*63:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__genblk1__BRA__4__KET____DOT__bm_chann_i__DOT__genblk1__BRA__15__KET____DOT__outp;
        IData/*31:0*/ memory[524288];
        IData/*31:0*/ sortmem[33];
        IData/*31:0*/ __PVT__M__DOT__x1[32];
        IData/*31:0*/ __PVT__M__DOT__y1[32];
        WData/*1023:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__intm_wires[6][32];
        CData/*0:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__validity[6];
        WData/*1023:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__int_wires[6][32];
        CData/*0:0*/ __PVT__M__DOT__genblk3__DOT__genblk2__DOT__M__DOT__genblk1__BRA__4__KET____DOT__sort_stage_inst__DOT__genblk1__BRA__0__KET____DOT__bm_i__DOT__validity[6];
    };
    
    // LOCAL VARIABLES
    CData/*0:0*/ __Vdly__mem_axi_arready;
    CData/*0:0*/ __Vdly__fast_raddr;
    CData/*0:0*/ __Vdly__mem_axi_awready;
    CData/*0:0*/ __Vdly__fast_waddr;
    CData/*0:0*/ __Vdly__mem_axi_wready;
    CData/*0:0*/ __Vdly__fast_wdata;
    CData/*0:0*/ __Vdly__mem_axi_rvalid;
    CData/*4:0*/ __Vdlyvlsb__memory__v0;
    CData/*7:0*/ __Vdlyvval__memory__v0;
    CData/*0:0*/ __Vdlyvset__memory__v0;
    CData/*4:0*/ __Vdlyvlsb__memory__v1;
    CData/*7:0*/ __Vdlyvval__memory__v1;
    CData/*0:0*/ __Vdlyvset__memory__v1;
    CData/*4:0*/ __Vdlyvlsb__memory__v2;
    CData/*7:0*/ __Vdlyvval__memory__v2;
    CData/*0:0*/ __Vdlyvset__memory__v2;
    CData/*4:0*/ __Vdlyvlsb__memory__v3;
    CData/*7:0*/ __Vdlyvval__memory__v3;
    CData/*0:0*/ __Vdlyvset__memory__v3;
    CData/*0:0*/ __Vdly__rst;
    CData/*0:0*/ __Vdly__now1;
    CData/*0:0*/ __Vdly__now2;
    CData/*0:0*/ __Vdly__mem_axi_bvalid;
    CData/*4:0*/ __Vdlyvlsb__memory__v4;
    CData/*7:0*/ __Vdlyvval__memory__v4;
    CData/*0:0*/ __Vdlyvset__memory__v4;
    CData/*4:0*/ __Vdlyvlsb__memory__v5;
    CData/*7:0*/ __Vdlyvval__memory__v5;
    CData/*0:0*/ __Vdlyvset__memory__v5;
    CData/*4:0*/ __Vdlyvlsb__memory__v6;
    CData/*7:0*/ __Vdlyvval__memory__v6;
    CData/*0:0*/ __Vdlyvset__memory__v6;
    CData/*4:0*/ __Vdlyvlsb__memory__v7;
    CData/*7:0*/ __Vdlyvval__memory__v7;
    CData/*0:0*/ __Vdlyvset__memory__v7;
    CData/*0:0*/ __Vdly__M__DOT__prev1;
    CData/*0:0*/ __Vdly__M__DOT__prev2;
    CData/*0:0*/ __Vdlyvset__M__DOT__x1__v0;
    IData/*31:0*/ __Vdly__mem_axi_rdata;
    IData/*18:0*/ __Vdlyvdim0__memory__v0;
    IData/*18:0*/ __Vdlyvdim0__memory__v1;
    IData/*18:0*/ __Vdlyvdim0__memory__v2;
    IData/*18:0*/ __Vdlyvdim0__memory__v3;
    IData/*31:0*/ __Vdly__din;
    IData/*18:0*/ __Vdlyvdim0__memory__v4;
    IData/*18:0*/ __Vdlyvdim0__memory__v5;
    IData/*18:0*/ __Vdlyvdim0__memory__v6;
    IData/*18:0*/ __Vdlyvdim0__memory__v7;
    IData/*31:0*/ __Vdly__M__DOT__cnt1;
    IData/*31:0*/ __Vdly__M__DOT__cnt2;
    
    // INTERNAL VARIABLES
  private:
    Vpicorv32_wrapper__Syms* __VlSymsp;  // Symbol table
  public:
    
    // CONSTRUCTORS
  private:
    VL_UNCOPYABLE(Vpicorv32_wrapper_axi4_mem_periph);  ///< Copying not allowed
  public:
    Vpicorv32_wrapper_axi4_mem_periph(const char* name = "TOP");
    ~Vpicorv32_wrapper_axi4_mem_periph();
    
    // INTERNAL METHODS
    void __Vconfigure(Vpicorv32_wrapper__Syms* symsp, bool first);
    static void _combo__TOP__picorv32_wrapper__mem__1(Vpicorv32_wrapper__Syms* __restrict vlSymsp);
    static void _combo__TOP__picorv32_wrapper__mem__13(Vpicorv32_wrapper__Syms* __restrict vlSymsp);
    static void _combo__TOP__picorv32_wrapper__mem__14(Vpicorv32_wrapper__Syms* __restrict vlSymsp);
    static void _combo__TOP__picorv32_wrapper__mem__8(Vpicorv32_wrapper__Syms* __restrict vlSymsp);
  private:
    void _ctor_var_reset() VL_ATTR_COLD;
  public:
    static void _initial__TOP__picorv32_wrapper__mem__7(Vpicorv32_wrapper__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    static void _sequent__TOP__picorv32_wrapper__mem__10(Vpicorv32_wrapper__Syms* __restrict vlSymsp);
    static void _sequent__TOP__picorv32_wrapper__mem__12(Vpicorv32_wrapper__Syms* __restrict vlSymsp);
    static void _sequent__TOP__picorv32_wrapper__mem__4(Vpicorv32_wrapper__Syms* __restrict vlSymsp);
    static void _sequent__TOP__picorv32_wrapper__mem__6(Vpicorv32_wrapper__Syms* __restrict vlSymsp);
    static void _sequent__TOP__picorv32_wrapper__mem__9(Vpicorv32_wrapper__Syms* __restrict vlSymsp);
    static void _settle__TOP__picorv32_wrapper__mem__11(Vpicorv32_wrapper__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    static void _settle__TOP__picorv32_wrapper__mem__2(Vpicorv32_wrapper__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    static void _settle__TOP__picorv32_wrapper__mem__3(Vpicorv32_wrapper__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    static void traceInit(VerilatedVcd* vcdp, void* userthis, uint32_t code);
    static void traceFull(VerilatedVcd* vcdp, void* userthis, uint32_t code);
    static void traceChg(VerilatedVcd* vcdp, void* userthis, uint32_t code);
} VL_ATTR_ALIGNED(VL_CACHE_LINE_BYTES);

//----------


#endif  // guard
